using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace hoppa.Service.Model
{
    public class Person
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        [Key]
        public string Guid { get; set; } = new Guid().ToString();

        public string DisplayName { get; set; } = string.Empty;                       

        [BsonDateTimeOptions]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        // possible connections

        public List<Connection> Connections { get; set; } 

        public List<Account> Accounts { get; set; }

        public List<Rule> Rules { get; set; }
    }

}
